; PlatformIO Project Configuration File
; VK Музыкальный Комбайн v1.0 (База: M5Stack Core2)

[platformio]
default_envs = m5stack-core2

[env:m5stack-core2]
platform = espressif32 @ 6.4.0
board = m5stack-core2
framework = arduino

; Включаем глубокий анализ локальных зависимостей в папке lib/
lib_ldf_mode = deep+

; Подключаем нашу новую таблицу разделов с поддержкой OTA
board_build.partitions = partitions.csv

; Флаги компиляции: максимальная скорость (-O3) и активация внешней PSRAM памяти
build_flags = 
    -O3
    -DCORE_DEBUG_LEVEL=0
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue

; Зависимости: скачиваем M5Unified, графический движок, асинхронный сервер и аудио-библиотеку
lib_deps = 
	lovyan03/LovyanGFX @ ^1.1.16
	lewisxhe/XPowersLib @ ^0.2.6
;	pschatzmann/ESP32-A2DP @ ^1.8.0
;    m5stack/M5Unified
;    m5stack/M5GFX
;    6853 @ ^3.3.2
;    earlephilhower/ESP8266Audio @ ^1.9.7
    https://github.com/mathieucarbou/ESPAsyncWebServer.git
;    https://github.com/ESP32Async/AsyncTCP.git

monitor_speed = 115200
monitor_filters = esp32_exception_decoder
